#preprod
deployment:
  user: jenkins
  from: ./
  to: /data/apps/eti_cdn/lucy/ti/app/
  excludes:
    - app
    - bin
    - src
    - templates
    - var
    - vendor
    - composer.lock
    - accueil.html
    - composer.json
    - gulpfile.js
    - phpunit.xml.dist
  strategy: targz
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - 10.25.109.32
tasks:
  pre-deploy:
  on-deploy:
    - chmod
    - cdn-tag
  post-release:
  post-deploy: