#preprod
deployment:
  user: jenkins
  from: ./
  to: /data/apps/eti_cdn/lucy/ti/app/
  excludes:
    - app
    - bin
    - src
    - templates
    - var
    - vendor
    - composer.lock
    - accueil.html
    - composer.json
    - gulpfile.js
    - phpunit.xml.dist
    - web/.htaccess
    - web/app.php
    - web/app_dev.php
    - web/apple-touch-icon.png
    - web/config.php
    - web/favicon.ico
    - web/robots.txt
    - web/scss
    - web/bundles
    - web/assets/maquettes
    - web/php
  strategy: targz
releases:
  enabled: true
  max: 3
  symlink: current
  directory: releases
hosts:
  - 10.25.109.32
tasks:
  pre-deploy:
  on-deploy:
    - chmod
  post-release:
  post-deploy:
    - cdn-tag
